### ISSUE TITLE
Issue with Package Path 

### ISSUE THREAD

**Issue by btcotter** [R-CoderDotCom/ggbernie#1]
Hello! 

I had a question regarding an error that I am getting while attempting to run the code. I downloaded all of the image files, set the working directory and path for them, and tried to run the code, but am experiencing an issue. When I attempt to trace back where the issue is, the system.file window notifies me that it is regarding "FILES <- file.path(packagePath, ...)". I am rather new to R, so I realize this may be a rather simple fix, but I was wondering if you happen to know where I went wrong with my code and what to do to fix this error? 

Thank you! 

I am pasting below what I have on my R script. It isn't very different than what was on here. 

```
library("ggplot2")
draw_key_bernie <-  function(data, params, size) {
  
  filename <- system.file(paste0(data$bernie, "sitting.png"), package = "ggbernie", mustWork = TRUE)
  # print(filename)
  img <- as.raster(png::readPNG(sitting))
  aspect <- dim(img)[1]/dim(img)[2]
  # rasterGrob
  grid::rasterGrob(image "sitting"= img)
}

bernieGrob <- function(x, y, size, bernie = "bernie1", geom_key = list(sitting = "sitting.png",
                                                                       stand = "stand.png",
                                                                       head = "head.png",
                                                                       asking = "asking.png",
                                                                       young = "young.png",
                                                                       arms = "arms.png",
                                                                       eyebrows = "eyebrows.png")) {
  
  filename <- system.file(geom_key[[unique(bernie)]], package = "ggbernie", mustWork = TRUE)
  img <- as.raster(png::readPNG(sitting.png))
  
  # rasterGrob
  grid::rasterGrob(x             = x,
                   y             = y,
                   image         = img,
                   # only set height so that the width scales proportionally and so that the icon
                   # stays the same size regardless of the dimensions of the plot
                   height        = size * ggplot2::unit(20, "mm"))
}


GeomBernie <- ggplot2::ggproto(`_class` = "GeomBernie",
                               `_inherit` = ggplot2::Geom,
                               required_aes = c("x", "y"),
                               non_missing_aes = c("size", "bernie"),
                               default_aes = ggplot2::aes(size = 1, bernie = "bernie1", shape  = 19,
                                                          colour = "black",   fill   = NA,
                                                          alpha  = NA,
                                                          stroke =  0.5,
                                                          scale = 5,
                                                          image_filename = "red"),
                               
                               draw_panel = function(data, panel_scales, coord, na.rm = FALSE) {
                                 coords <- coord$transform(data, panel_scales)
                                 ggplot2:::ggname(prefix = "geom_bernie",
                                                  grob = bernieGrob(x = coords$x,
                                                                    y = coords$y,
                                                                    size = coords$size,
                                                                    bernie = coords$bernie))
                               },
                               
                               draw_key = draw_key_bernie)
geom_bernie <- function(mapping = NULL,
                        data = NULL,
                        stat = "identity",
                        position = "identity",
                        ...,
                        na.rm = FALSE,
                        show.legend = NA,
                        inherit.aes = TRUE) {
  
  ggplot2::layer(data = data,
                 mapping = mapping,
                 stat = stat,
                 geom = GeomBernie,
                 position = position,
                 show.legend = show.legend,
                 inherit.aes = inherit.aes,
                 params = list(na.rm = na.rm, ...))
}

ggplot(mtcars) +
  geom_bernie(aes(mpg, wt), bernie = "bernie1")
```

**Comment by R-CoderDotCom** [comment]
Hi, what are you trying to do?

If you want to use the package just install it. You don't need to download all the files, just install it with:

```
# install.packages("remotes")
remotes::install_github("R-CoderDotCom/ggbernie@main")
```
If you are trying to understand the source code and run it by yourself you need to create an R package and compile it to use the functions.

**Comment by btcotter** [comment]
Hello, 

Thank you for your response! This was super helpful. I went ahead and downloaded it. However, when I load the script for "ggplot(mtcars") it notifies me that:
Error in system.file(geom_key[[unique(bernie)]], package = "ggbernie",  : 
  no file found

Am I missing something here? I went ahead and set the working directory to where the file is. I'm sure I'm just missing a simple step. I'm sorry for the inconvenience but any advice would be greatly appreciated!

Thank you!

**Comment by R-CoderDotCom** [comment]
What to you mean by loading the script for "ggplot(mtcars)"?

I'm not sure if I'm understanding your issue, so I'm going to explain basic concepts and how this package works:

1. Open R and install the package on your computer

```
# install.packages("remotes")
remotes::install_github("R-CoderDotCom/ggbernie@main")
```

2. Load the package

```r
library(ggbernie)
```

3. Create a BerniePlot

```r
library(ggplot2)  # Because ggplot function comes from this package

ggplot(mtcars) +
  geom_bernie(aes(mpg, wt), bernie = "sitting")
```

![ggbernie](https://user-images.githubusercontent.com/67192157/105496237-80897b00-5cbd-11eb-996a-b77e89011b31.png)

And thats all you need to use the package. Maybe you missed loading ggplot2 library?

Now, if you really want to download all the files you will need to create a new package with `usethis::create_package("new_package")`, put all the files there, compile the package and you will be able to use the function from `new_package`.

**Comment by btcotter** [comment]
Hello,

Thank you for your reply!

I did all of the steps you outlined below and am still coming across the same issue. It appears as if “sitting.png” is not being recognized. I get the error message: “Error in png::readPNG(sitting.png) : object 'sitting.png' not found”

Is there a step I’m missing to load the image file? It’s currently on my desktop and I set the working directory to my desktop, so not sure what more I should do to be able to get the plot.

Thanks!

Best,
Beverly

***************************
Beverly T. Cotter
Graduate Student, Ferreira Lab
GSA Rep, PsychSA
Department of Psychology

Pronouns: she/her/hers

University of California, Davis
200 E. Quad
Davis, CA 95616

E: btcotter@ucdavis.edu<mailto:btcotter@ucdavis.edu>

**Comment by R-CoderDotCom** [comment]
Several people has posted their own Bernie plots on Twitter. You should be able to use the package as any other if you follow the steps I outlined. 

However, I've noticed that the code you posted on the first comment doesn't make any sense.

This line  `img <- as.raster(png::readPNG(sitting))` and `grid::rasterGrob(image "sitting"= img)` both will throw errors. The first because `sitting` should be `"sitting.png"` and the second doesn't make any sense at all. It seems you have tried replacing some code with other and that happened.

> I am pasting below what I have on my R script. It isn't very different than what was on here.

Why are you using your own code?

In your last comment you say that you are getting this error:

> “Error in png::readPNG(sitting.png) "

This line on code doesn't appear on the package source either. This is part of your code from your first comment (I will asumme you are trying to implement your own geom without understanding basic R programming concepts and how a package actually works ¿?). This line doesn't work because sitting.png needs to be quoted or R will look for an object with that name.

I'm going to close this issue because you are asking for help not related to the package itself. There are lots of resources available on the internet about [creating new R packages](https://r-pkgs.org/) and [new geoms](https://ggplot2.tidyverse.org/articles/extending-ggplot2.html). If you want to create your own geom and you don't now how consider asking me via [Twitter](https://twitter.com/RCoderWeb/) or via mail and if it is something intersting or funny I will create it.

Best regards

**Comment by btcotter** [comment]
Thank you for your help, I do really appreciate it.

I recognize the code I posted on my first comment is incorrect, I fixed it once you helped me in the second reply, so the code in the first email is no longer relevant to my new question. I used the same exact code that was pasted on github and followed the exact instructions that you had sent me, and those that were posted online. I still received the same exact error that I had sent in my most recent reply.

I understand that beyond this it is not fair to receive help on basic R programming skills. I am a first year graduate student. I am still learning, so I am sorry if I ever bothered you with my questions. I was able to figure it out.

Thanks.

**Comment by R-CoderDotCom** [comment]
Hi, don't worry about that. I didn't mean to be rude. I'm going to try explaining some concepts:

- You can't use **this package** copying and pasting the functions, because of this lines: `filename <- system.file(paste0(data$bernie, ".png"), package = "ggbernie", mustWork = TRUE)` and `filename <- system.file(geom_key[[unique(bernie)]], package = "ggbernie", mustWork = TRUE)`. This lines look for the corresponding image **inside the package**, so `ggbernie` must be installed on your computer.

- The latter means that if you copy and paste all the folders, images, codes and files of the package, set your working directory and you run the code, R won't find the images. You would need to create an R package and compile it, but that is something advanced.

- The last error you posted: “Error in png::readPNG(sitting.png) : object 'sitting.png' not found” says that there is an error with this line: `png::readPNG(sitting.png)`, but that line doesn't appear on the source code of the package. You can check this here: https://github.com/R-CoderDotCom/ggbernie/blob/main/R/ggbernie.R

- The error you are experiencing tells me that (maybe) you have your own function stored in your R session, so when you call `geom_bernie`, R is using the function you created (if you restart R the workspace should be restored, but maybe you saved it). When you have several functions with the same name on your working directory you can use the `::` operator to indicate from which package the function is taken. In this case, to make sure that you are running the correct function type `ggbernie::geom_bernie` instead of `geom_bernie`.


So... how can you solve the error?

I recommend you to install the latest version of R. If you already have it open R and type the following in the console:

```r
# Remove all from the workspace
rm(list = ls())

# Package needed to install packages from GitHub
install.packages("remotes")

# From remotes, use install_github function to download and install ggbernie from the repo
remotes::install_github("R-CoderDotCom/ggbernie@main")
# (Check that the package was installed properly)

# Package needed to create ggplots
install.packages("ggplot2")

# Load ggplot2 library
library(ggplot2)

# Load ggbernie library
library(ggbernie)


# Nice, lets try creating a plot with ggplot2
ggplot(mtcars) + 
     geom_point(aes(mpg, wt))


# Now lets use ggbernie (ggbernie::geom_bernie to make sure you are using the correct function)
ggplot(mtcars) +
  ggbernie::geom_bernie(aes(mpg, wt), bernie = "sitting")
```
This should work but if not, I recommend you to ask someone you know with experience with R code to see whats going on.



Things you can do to practise more R:

Try installing the new package I posted (https://github.com/R-CoderDotCom/ggcats), https://github.com/coolbutuseless/geomlime/ or https://mran.microsoft.com/snapshot/2018-05-23/web/packages/ggimage/vignettes/ggimage.html and try running some examples. All these packages work almost the same way so you should be able to use them.You can also check other libraries I developed, specially [calendR](https://github.com/R-CoderDotCom/calendR) because is pretty straightforward to use.

Hope you make this work! I also started learning R when I was a first year graduate student (3 years ago), so do not be discouraged because we all were where you are now.

Best regards
